### ISSUE TITLE
Not an issue, but suggestion - add a whitelist?

### ISSUE THREAD

**Issue by Solwithabat** [nextu1337/hypixel-fragbot#1]
I think it would be nice if we could toggle between a whitelist/blacklist, great project though - super useful tysm.

**Comment by 2xxn** [comment]
Thanks for your input! While your suggestion was different, I still decided to make a change based on it. Instead of making a toggle, I replaced it with a whitelist entirely. This change makes sense as this repository is meant for personal use rather than a mass use. Please check out the updated README to see how the new version works. Thanks for using my repo!

Also, I apologize for spamming with commits. I'll switch to using Git soon.
